routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Artist;
use App\Models\Album;
use App\Models\Playlist;
use App\Models\Track;
use Illuminate\Support\Facades\Route;
use App\Http\Resources\UserResource;
use App\Http\Resources\ArtistResource;
use App\Http\Resources\AlbumResource;
use App\Http\Resources\AlbumSummaryResource;
use App\Http\Resources\TrackResource;
use App\Http\Resources\PlaylistResource;


Route::get('/logout', 'Auth\LoginController@logout');

/**
 * App routes
 */


Route::get('/', 'MusicController@home');

Route::prefix('app')->group(function() {
  Route::get('{any?}/{route?}', 'MusicController@home');
  Route::get('/playlist/{playlist}/edit', 'MusicController@home');
});


/**
 * File serving routes
 */
Route::get('/files/tracks/{track}.mp3', 'FileController@stream_track');
Route::get('/files/artwork/{album}.jpg', 'FileController@serve_artwork');


/**
 * uploading and editing music routes
 */
Route::prefix('admin')->middleware('role:admin|uploader')->group(function () {

  Route::get('/', 'MusicController@index')->name('admin');

  Route::get('/upload', 'UploadController@index')->name('upload');
  Route::post('/upload', 'UploadController@upload');

  Route::get('/albums', 'MusicController@albums');
  Route::get('/albums/edit', 'MusicController@editAlbumList')->name('editAlbums');
  Route::get('/albums/album/{album}/edit', 'MusicController@editAlbum');
  Route::post('/albums/album/{album}/edit', 'MusicController@editAlbumSubmit');

  Route::get('/tracks', 'MusicController@tracks');
  Route::get('/tracks/edit', 'MusicController@editTrackList')->name('editTracks');
  Route::get('/tracks/track/{track}/edit', 'MusicController@editTrack');
  Route::post('/tracks/track/{track}/edit', 'MusicController@editTrackSubmit');

  Route::get('/artists', 'MusicController@artists');
  Route::get('/artists/edit', 'MusicController@editArtistList')->name('editArtists');
  Route::get('/artists/artist/{artist}/edit', 'MusicController@editArtist');
  Route::post('/artists/artist/{artist}/edit', 'MusicController@editArtistSubmit');

  Route::get('/unprocessed-tracks', 'MusicController@unprocessed_tracks')->name('unprocessedTracks');
  Route::post('/unprocessed-tracks', 'MusicController@process_tracks');


});


/**
 * routes for editing users
 */
Route::prefix('admin')->middleware('role:admin')->group(function () {

    Route::resource('user', 'UserController');

});

/**
 * api routes
 */
Route::prefix('api/v1')->group(function () {

  Route::get('user', function () {
      return new UserResource(Auth::user());
  });
  Route::post('user', 'APIController@update_user');

  Route::post('search', 'SearchController@index');
  // get single
  Route::get('artist/{artist}', function (Artist $artist) {
      return new ArtistResource($artist);
  });
  Route::get('album/{album}', function (Album $album) {
      return new AlbumResource($album);
  });
  Route::get('track/{track}', function (Track $track) {
      return new TrackResource($track);
  });

  // get paginated results
  Route::get('artists/{page?}', function ($page) {
      $artists = Artist::where('id', '!=', 1)
        ->simplePaginate(50, [] , '', $page);
      return ArtistResource::collection($artists);
  });

  Route::get('albums/{page?}', function () {
      $albums = Album::where('id', '!=', '1')
        ->simplePaginate(25, ['*'] , '');
      return AlbumSummaryResource::collection($albums);
  });

  Route::get('tracks/{page?}', function () {

  });

  /**
   * playlist api
   */

  Route::resource('playlist', 'PlaylistController', [
    'except' => ['create', 'edit']
  ]);
  Route::resource('playlist/{playlist}/item', 'PlaylistItemController', [
    'except' => ['index', 'create', 'update', 'show']
  ]);

});

Auth::routes();

resources/views/structures/admin-header.blade.php
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Right Side Of Navbar -->
            @include ('structures.admin-menu')
        </div>
    </div>
</nav>
@ability('admin,uploader', '')
    @include ('structures.admin-tabs')
@endability

resources/views/structures/admin-menu.blade.php
<ul class="nav navbar-nav navbar-right">
    <!-- Authentication Links -->
    @auth
        <li>
            <a href="">
                {{ Auth::user()->name }}
            </a>
        </li>
        @ability('admin,uploader', '')
        <li class="dropdown">
            <a class="dropdown-toggle" id="nav-dropdown" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="true">
                <i class="glyphicon glyphicon-cog"></i>
                <i class="glyphicon glyphicon-chevron-down"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
                <li><a href="{{ route('upload') }}">Upload</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{{ route('unprocessedTracks') }}">Unprocessed tracks</a></li>
                <li><a href="{{ route('editTracks') }}">Edit tracks</a></li>
                <li><a href="{{ route('editAlbums') }}">Edit albums</a></li>
                <li><a href="{{ route('editArtists') }}">Edit artists</a></li>
                <li role="separator" class="divider"></li>
                @role('admin')
                <li><a href="{{ route('user.index') }}">User administration</a></li>
                <li role="separator" class="divider"></li>
                @endrole
                <li>
                    <a href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                        Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </li>
        @endability
        @endguest
</ul>

resources/views/structures/admin-styles.blade.php
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link href="{{ asset('css/jquery-ui.min.css') }}" rel="stylesheet">
<link href="{{ asset('css/jquery-ui.theme.min.css') }}" rel="stylesheet">

resources/views/structures/admin-tabs.blade.php
<ul class="m-admin-actions nav nav-tabs">
    <li class="nav-item {{ (Route::currentRouteName() === 'upload') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('upload' )}}">Track upload</a>
    </li>
    <li class="nav-item {{ (Route::currentRouteName() === 'unprocessedTracks') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('unprocessedTracks') }}">Unprocessed tracks</a>
    </li>
    <li class="nav-item {{ (Route::currentRouteName() === 'editTracks') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('editTracks') }}">Track edit</a>
    </li>
    <li class="nav-item {{ (Route::currentRouteName() === 'editAlbums') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('editAlbums') }}">Album edit</a>
    </li>
    @role('admin')
    <li class="nav-item {{ (strpos(Route::currentRouteName(), 'user.') !== FALSE) ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('user.index') }}">User Admin</a>
    </li>
    @endrole
</ul>

resources/views/structures/app-footer.blade.php
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js')}}"></script>
<script src="{{ asset('js/admin.js') }}"></script>

<!-- Vue templates -->
<script type="application/x-javascript"></script>

resources/views/structures/app-header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                <div id="search-app"></div>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @auth
                    <li>
                        <a href="">
                            {{ Auth::user()->name }}
                        </a>
                    </li>
                    <li class="dropdown">
                        <a class="btn btn-sm"
                           aria-expanded="true" href="/admin">
                            <i class="glyphicon glyphicon-cog"></i>
                            admin
                        </a>
                    </li>
                    @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/structures/footer.blade.php
<!-- Scripts -->

<script src="{{ asset('js/admin.js') }}"></script>
<script src="{{ asset('js/jquery-ui.min.js')}}"></script>

@yield('scripts')

resources/views/structures/messages.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

resources/views/structures/table.blade.php
<table class="table">
    <thead>
        <tr>
            @foreach ($headers as $header)
                <th>
                    {!! $header !!}
                </th>
            @endforeach
        </tr>
    </thead>
    <tbody>
        @foreach ($rows as $row)
            <tr>
                @foreach ($row as $field)
                    <td>
                        {!! $field !!}
                    </td>
                @endforeach
            </tr>
        @endforeach
    </tbody>

</table>